### ISSUE TITLE
Support replicating view definitions

### ISSUE THREAD

**Issue by spuranda123** [HotelsDotCom/circus-train#100]
DSP Jetstream uses CT as a replication tool. We came across a scenario where we would like to know if CT can support replicating view definitions as it might be a potential use case in future.

**Comment by massdosage** [comment]
Please use the Mailing List for asking questions and general discussion:

https://github.com/HotelsDotCom/circus-train#mailing-list

Thanks.

**Comment by patduin** [comment]
https://github.com/HotelsDotCom/circus-train#replicate-a-view

;)
