### ISSUE TITLE
Install link from read me is returning 404

### ISSUE THREAD

**Issue by rkkalluri** [HotelsDotCom/circus-train#12]
http://mvnrepository.com/artifact/com.hotels/circus-train/circus-train-package is returning 404 this is the link provided in readme for Install section, can we provide a valid link to download the .tgz or rpm.

**Comment by patduin** [comment]
oops you've found a wrong link:
Try http://mvnrepository.com/artifact/com.hotels/circus-train that should get you to the correct place, there is a tgz package.
We'll fix the readme thanks for reporting.

**Comment by patduin** [comment]
I've updated the link, thanks again.
