### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [HotelsDotCom/circus-train#136]
Hi
The following lines have cryptographic API misuses. <br> File name => circus-train-comparator/src/main/java/com/hotels/bdp/circustrain/comparator/hive/functions/PathDigest.java: Line number => 49: API name => MessageDigest:Operation on object of type java.security.MessageDigest object not completed. Expected call to digest, update<BR>

**Comment by massdosage** [comment]
`digest()` is called on line 57 so I don't think this issue is valid.
