### ISSUE TITLE
Provide sts assume role support for s3-s3 copier

### ISSUE THREAD

**Issue by patduin** [HotelsDotCom/circus-train#151]
_As a user of CT_
_I'd like to configure ct with a user arn for source and target_
_So that CT can assume the correct role when reading and writing data_

Similar to what we provide to s3MapReduceCopier we should allow the sts assume credentials provider to be configured. 
It should be configurable on source and target with different settings.

**Comment by massdosage** [comment]
Code changes will probably be very similar to the other half of https://github.com/HotelsDotCom/circus-train/pull/105/files <- this changed both the `S3MapReduceCopier` (which has already been done in the PR referenced above) and the `S3S3Copier` (what needs to happen here).
