### ISSUE TITLE
If table has large number of partitions to replicate, Replica.updateMetadata should send partition list in batches

### ISSUE THREAD

**Issue by barnharts4** [HotelsDotCom/circus-train#166]
**Is your feature request related to a problem? Please describe.**
When replicating a table with over 40,000 partitions, replication fails in `Replica.updateMetadata` with a timeout on the Hive metastore, due to sending a `List<Partition>` of size 40000 in one thrift request.

**Describe the solution you'd like**
The list of partitions to be added/altered should be broken up into manageable batch sizes so as not to overwhelm the hive metastore with a huge request.

**Comment by patduin** [comment]
Thanks for contributing!
