### ISSUE TITLE
Select Copier using yaml file

### ISSUE THREAD

**Issue by yashrajrs** [HotelsDotCom/circus-train#55]
Currently the copier is decided based on the location paths.
So if the replication is from s3 to s3  https://github.com/HotelsDotCom/circus-train/blob/master/circus-train-s3-s3-copier/src/main/java/com/hotels/bdp/circustrain/s3s3copier/S3S3Copier.java is used.

I wish to use for https://github.com/HotelsDotCom/circus-train/blob/master/circus-train-s3-mapreduce-cp-copier/src/main/java/com/hotels/bdp/circustrain/s3mapreducecpcopier/S3MapReduceCpCopier.java for s3 to s3 replication.

Two possible solutions:- 
1.)  add a config for picking the copier by class name

2.) add a general config like “preferMR”: true and S3S3Copier returns false if that’s true

**Comment by ddcprg** [comment]
Merged in #57
