### ISSUE TITLE
Generic keystore implementation 

### ISSUE THREAD

**Issue by revinjchalil** [HotelsDotCom/circus-train#84]
The access.key and secret.key are currently expected from the hadoop credentials provider (JCEKS) and so other filesystems including Azure Blob storage which has a different key structure does not work. It might be beneficial to allow the user to provide a mapping that allows the fetch of a user defined key from JCEKS into the configuration. 

Below is the sample Azure Blob storage key structure.

fs.azure.account.key.xxxxxx.blob.core.windows.net=yyyyyyyyyyy+O1HSAQ8odCgjiXst9QJkt7lVy8nuDfhFbgYLgmBg2NJF9cqPftKQ== 

From AWSConstants.java
-------------------------
  public static final String ACCESS_KEY = "access.key";
  public static final String SECRET_KEY = "secret.key";

From setS3CredentialsUtils.java:
--------------------------------

public void setS3Credentials(Configuration conf) {
  String accessKey = getKey(conf, ACCESS_KEY);
  String secretKey = getKey(conf, SECRET_KEY);

  conf.set("fs.s3.awsAccessKeyId", accessKey);
  conf.set("fs.s3.awsSecretAccessKey", secretKey);

From AWSCredentialUtils.java:
--------------------------------

static String getKey(Configuration conf, String keyType) {
  checkNotNull(conf, "conf cannot be null");
  checkNotNull(keyType, "KeyType cannot be null");

  try {
    char[] key = conf.getPassword(keyType);
    if (key == null) {
      throw new IllegalStateException(format("Unable to get value of '%s'", keyType));
    }

**Comment by massdosage** [comment]
This sounds like a good idea to make the loading of Credentials customisable. Hopefully we can put the above behind a set of interfaces and then depending on what's available on the classpath (or configured somehow) we would load up a specific "Credentials loader" implementation which would do whatever is necessary for that particular platform. [Extension Points](https://github.com/HotelsDotCom/circus-train#extension-points) could provide some starting points for how we allow for other aspects of Circus Train to be customised.

**Comment by patduin** [comment]
@revinjchalil The classes that you mention are what's setting all the credentials in the HiveConf that's later used by CT do launch hadoop job for replication or do direct Fileystem manipulation.
As you've seen it's very geared towards AWS and not very configurable at the moment. It all get triggered by the inclusion of this setting.
```
    security:
      credential-provider: <jceks>

``` 
In the yaml configuration.
How this works is that we set the following in com.hotels.bdp.circustrain.context.CommonBeans
```
 private void setCredentialProviderPath(Security security, Map<String, String> properties) {
    if (security.getCredentialProvider() != null) {
      // TODO perhaps we should have a source catalog scoped credential provider instead on one specific to S3?
      properties.put(CREDENTIAL_PROVIDER_PATH, security.getCredentialProvider());
    }
  }
```
As you can see from the TODO we dabbled with the idea of handling this better, we just never got around.
Another key component is this class com.hotels.bdp.circustrain.aws.context.AWSBeanPostProcessor. It is a spring bean post processor that we use to check if above property was set and if so we set all the AWS credentials in the conf.

From a quick glance it looks like some of the classes are not very AWS specific in the circus-train-aws module and might be better of move to a place where they can be reused for setting Azure/Custom credentials.

As @massdosage suggested it would be good to have it all hidden behind something like a CredentialsLoader that can be configured using com.hotels.bdp.circustrain.api.conf.Security.

Let us know if you're ok having a stab at this, we'll be happy to review or help design it further.

**Comment by massdosage** [comment]
Closing since we haven't had any input on this ticket for months, we can re-open if/when we decide to make the credentials more generic.
