### ISSUE TITLE
Wrongly parsed column values by Circus Train

### ISSUE THREAD

**Issue by andrispalfi** [HotelsDotCom/circus-train#90]
During our GCP-AWS migration tasks we realized that there are separate column values which are not parsed appropriately by Circus Train. For example in one of the tables that we would like to migrate to AWS from GCP we have a similar value like this:

columnB = """{""""abcd"""":""""efgh1234""""","""""abcd"""":""""dcba1234""""}"""

Circus Train will split this value up along the comma. So in the output CSV we will get this separation:

columnA: ""
columnB: "{""abcd"":""efgh1234""
columnC: ""abcd"":""dcba1234""}"
columnD: ""

Landing table properties are:

ROW FORMAT SERDE 
  'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ( 
'field.delim'=',',
'serialization.format'=',',
'skip.header.line.count'='1')
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat'
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'

I've tried to use OpenCSVSerde with ',' as separatorChar and '"' as quoteChar on the landing table on AWS, but it did not solve the issue entirely.
There are some cases when it would be great to have other than e.g. comma as a separator char in the output CSV.

**Comment by massdosage** [comment]
@andrispalfi this isn't an issue in core Circus Train, but rather in the Big Query integration which can be found here: 

https://github.com/HotelsDotCom/circus-train-bigquery

Could you please recreate this issue over there?
