### ISSUE TITLE
Cross-Account Replications Don't Set Bucket Owner Permissions

### ISSUE THREAD

**Issue by baumandm** [HotelsDotCom/circus-train#99]
We are attempting to replicate tables into buckets owned by a separate AWS account, and the files are being written without permissions for the bucket owner.  Circus Train succeeds and the files are copied, but the bucket owner account is unable to query the data.

More information about this issue can be found here:
https://aws.amazon.com/premiumsupport/knowledge-center/s3-bucket-owner-access/

We tried applying an [EMR setting](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-s3-acls.html) to set a canned ACL but it didn't seem to affect the Circus Train putObjects.

The other solution is for Circus Train to apply a canned ACL that gives the bucket owner permission on the files.  This could be an optional configuration, but it may be a suitable default as it seems less likely that one would want to replicate into a separate account's bucket and retain ownership.

I think it would require a change [here](https://github.com/HotelsDotCom/circus-train/blob/533cfbbddba0925d894a1498e06a7a2b58c8f6c5/circus-train-s3-mapreduce-cp/src/main/java/com/hotels/bdp/circustrain/s3mapreducecp/mapreduce/RetriableFileCopyCommand.java#L158) like this

    PutObjectRequest request = new PutObjectRequest(uploadDescriptor.getBucketName(), uploadDescriptor.getKey(), 
          input, uploadDescriptor.getMetadata());
    request.withCannedAcl(CannedAccessControlList.BucketOwnerFullControl);

**Comment by massdosage** [comment]
@baumandm that looks reasonable, does it have any impact when you're replicating into your own AWS account (e.g. from HDFS). Not sure if this would widen the permissions in any undesirable way? 

If it won't impact any existing replications then I'm fine with this being the new default behaviour and not making it configurable. On the other hand if this could alter existing behaviour it probably wouldn't take too much effort to add it as a configurable `copier-option` and then allow the user to optionally specify one of the predefined Canned ACLs provided by AWS.

This should probably also be added to https://github.com/HotelsDotCom/circus-train/blob/master/circus-train-s3-s3-copier/src/main/java/com/hotels/bdp/circustrain/s3s3copier/S3S3Copier.java#L156 for the case where we copy between S3 locations.

Do you have time to raise a PR with the above changes? If not we can try take it into our next sprint.

**Comment by baumandm** [comment]
It seems unlikely that anyone is currently using Circus Train to replicate data into an S3 bucket they don't own, while retaining ownership of the data such that the owner of the S3 bucket cannot read the data.  So it seems like a sensible default but would technically be a breaking change.

I can also see some value in having an option for selecting any of the Canned ACLs, but it's less likely that we will have a use case for any of the others.

I can try to raise a PR for this.

**Comment by massdosage** [comment]
@baumandm I'm assuming you haven't taken a further look at this yet? If not I'll have a go at making this configurable but it would be great if you could test out a snapshot for us as it's a bit tricky to test cross-account access

**Comment by baumandm** [comment]
I actually started on this yesterday, hoping to test it today and have a PR ready by the end of the week.

**Comment by massdosage** [comment]
OK, I'll leave it with you for now then, cool!
